project:
  type: website

website:
  title: "Questionnaire for Designing Small Plot Trials"
  favicon: images/AAGI_logo.png
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



