name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
  - cron: '0 1 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
# checkout code
      - name: Check out repository
        uses: actions/checkout@v4

# Set up Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
# set up R with specific version
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1' # use r version 4.4.0

# install R Dependencies
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

# install MASS explicitly to make sure its available
      - name: install MASS
      run: | 
      R -e "install.packages ('MASS')" #install MASS manually

# Render and publish
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_USERNAME: ${{ secrets.MY_USERNAME_GHA }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD_GHA }}
          
          
          
          